-- Custom SQL migration file, put your code below! --
INSERT INTO "concepts" ("name", "icon") VALUES
  ('rent', 'house'),
  ('telephone', 'smartphone'),
  ('misc', 'celebration'),
  ('unexpected debt', 'universal-currency-alt'),
  ('debt', 'payments'),
  ('subscription', 'live-tv'),
  ('savings', 'savings'),
  ('supermarket', 'shopping-cart'),
  ('investment', 'query-stats'),
  ('ingress', 'attach-money'),
  ('gym', 'exercise'),
  ('transport', 'train'),
  ('travels', 'flight'),
  ('restaurant', 'local-pizza'),
  ('electricity', 'emoji-objects'),
  ('water', 'water-drop'),
  ('gas', 'local-fire-department'),
  ('gasoline', 'local-gas-station'),
  ('internet', 'wifi');
